;; マーク中ならその部分を、そうでないならカレントラインを移動
;; M-up M-downで

(defun move-line-up()
  (interactive)
  (let ((selected-line))
    (if (region-active-p)
        (setq selected-line (buffer-substring (region-beginning) (region-end)))
      (setq selected-line (buffer-substring (point-at-bol)(point-at-eol)))
      (set-mark (point-at-bol))
      (end-of-line))
    (delete-region (region-beginning) (region-end))
    (delete-char 1)
    (beginning-of-line)
    (previous-line)
    (insert selected-line)
    (newline)
    (previous-line)))

(defun move-line-down()
  (interactive)
  (let ((selected-line))
    (if (region-active-p)
        (setq selected-line (buffer-substring (region-beginning) (region-end)))
      (setq selected-line (buffer-substring (point-at-bol)(point-at-eol)))
      (set-mark (point-at-bol))
      (end-of-line))
    (delete-region (region-beginning) (region-end))
    (delete-char 1)
    (beginning-of-line)
    (next-line)
    (insert selected-line)
    (newline)
    (previous-line)))

(provide 'move-line)
